package com.wentao.ncov.entity.mysql;

import java.util.Date;

public class AreaData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.id
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.province_Name
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.province_Short_Name
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String provinceShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.country
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String confirmedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.suspected_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String suspectedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.cured_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String curedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.dead_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String deadCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.location_Id
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.update_Time
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.current_Confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String currentConfirmedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.new_Confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String newConfirmedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.sure_Nzd_Cnt
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    private String sureNzdCnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.id
     *
     * @return the value of area_data.id
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.id
     *
     * @param id the value for area_data.id
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.province_Name
     *
     * @return the value of area_data.province_Name
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.province_Name
     *
     * @param provinceName the value for area_data.province_Name
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.province_Short_Name
     *
     * @return the value of area_data.province_Short_Name
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getProvinceShortName() {
        return provinceShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.province_Short_Name
     *
     * @param provinceShortName the value for area_data.province_Short_Name
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setProvinceShortName(String provinceShortName) {
        this.provinceShortName = provinceShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.country
     *
     * @return the value of area_data.country
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.country
     *
     * @param country the value for area_data.country
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.confirmed_Count
     *
     * @return the value of area_data.confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getConfirmedCount() {
        return confirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.confirmed_Count
     *
     * @param confirmedCount the value for area_data.confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setConfirmedCount(String confirmedCount) {
        this.confirmedCount = confirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.suspected_Count
     *
     * @return the value of area_data.suspected_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getSuspectedCount() {
        return suspectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.suspected_Count
     *
     * @param suspectedCount the value for area_data.suspected_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setSuspectedCount(String suspectedCount) {
        this.suspectedCount = suspectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.cured_Count
     *
     * @return the value of area_data.cured_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getCuredCount() {
        return curedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.cured_Count
     *
     * @param curedCount the value for area_data.cured_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setCuredCount(String curedCount) {
        this.curedCount = curedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.dead_Count
     *
     * @return the value of area_data.dead_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getDeadCount() {
        return deadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.dead_Count
     *
     * @param deadCount the value for area_data.dead_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setDeadCount(String deadCount) {
        this.deadCount = deadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.location_Id
     *
     * @return the value of area_data.location_Id
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.location_Id
     *
     * @param locationId the value for area_data.location_Id
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.update_Time
     *
     * @return the value of area_data.update_Time
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.update_Time
     *
     * @param updateTime the value for area_data.update_Time
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.current_Confirmed_Count
     *
     * @return the value of area_data.current_Confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getCurrentConfirmedCount() {
        return currentConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.current_Confirmed_Count
     *
     * @param currentConfirmedCount the value for area_data.current_Confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setCurrentConfirmedCount(String currentConfirmedCount) {
        this.currentConfirmedCount = currentConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.new_Confirmed_Count
     *
     * @return the value of area_data.new_Confirmed_Count
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getNewConfirmedCount() {
        return newConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.new_Confirmed_Count
     *
     * @param newConfirmedCount the value for area_data.new_Confirmed_Count
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setNewConfirmedCount(String newConfirmedCount) {
        this.newConfirmedCount = newConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.sure_Nzd_Cnt
     *
     * @return the value of area_data.sure_Nzd_Cnt
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public String getSureNzdCnt() {
        return sureNzdCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.sure_Nzd_Cnt
     *
     * @param sureNzdCnt the value for area_data.sure_Nzd_Cnt
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    public void setSureNzdCnt(String sureNzdCnt) {
        this.sureNzdCnt = sureNzdCnt;
    }
}
