package com.wentao.ncov.entity.mysql;

import java.util.Date;

public class AreaData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.id
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.province_Name
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.province_Short_Name
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private String provinceShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.country
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.confirmed_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private Integer confirmedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.suspected_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private Integer suspectedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.cured_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private Integer curedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.dead_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private Integer deadCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.location_Id
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_data.update_Time
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.id
     *
     * @return the value of area_data.id
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.id
     *
     * @param id the value for area_data.id
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.province_Name
     *
     * @return the value of area_data.province_Name
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.province_Name
     *
     * @param provinceName the value for area_data.province_Name
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.province_Short_Name
     *
     * @return the value of area_data.province_Short_Name
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public String getProvinceShortName() {
        return provinceShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.province_Short_Name
     *
     * @param provinceShortName the value for area_data.province_Short_Name
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setProvinceShortName(String provinceShortName) {
        this.provinceShortName = provinceShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.country
     *
     * @return the value of area_data.country
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.country
     *
     * @param country the value for area_data.country
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.confirmed_Count
     *
     * @return the value of area_data.confirmed_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public Integer getConfirmedCount() {
        return confirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.confirmed_Count
     *
     * @param confirmedCount the value for area_data.confirmed_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setConfirmedCount(Integer confirmedCount) {
        this.confirmedCount = confirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.suspected_Count
     *
     * @return the value of area_data.suspected_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public Integer getSuspectedCount() {
        return suspectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.suspected_Count
     *
     * @param suspectedCount the value for area_data.suspected_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setSuspectedCount(Integer suspectedCount) {
        this.suspectedCount = suspectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.cured_Count
     *
     * @return the value of area_data.cured_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public Integer getCuredCount() {
        return curedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.cured_Count
     *
     * @param curedCount the value for area_data.cured_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setCuredCount(Integer curedCount) {
        this.curedCount = curedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.dead_Count
     *
     * @return the value of area_data.dead_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public Integer getDeadCount() {
        return deadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.dead_Count
     *
     * @param deadCount the value for area_data.dead_Count
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setDeadCount(Integer deadCount) {
        this.deadCount = deadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.location_Id
     *
     * @return the value of area_data.location_Id
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.location_Id
     *
     * @param locationId the value for area_data.location_Id
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_data.update_Time
     *
     * @return the value of area_data.update_Time
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_data.update_Time
     *
     * @param updateTime the value for area_data.update_Time
     *
     * @mbggenerated Mon Feb 10 18:11:22 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}