package com.wentao.ncov.entity.mysql;

import java.util.Date;

public class NationalData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.id
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.confirmed_Count
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String confirmedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.confirmed_Count_Incr
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String confirmedCountIncr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.suspected_Count
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String suspectedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.suspected_Count_Incr
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String suspectedCountIncr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.cured_Count
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String curedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.cured_Count_Incr
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String curedCountIncr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.dead_Count
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String deadCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.dead_Count_Incr
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private String deadCountIncr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column National_Data.create_Time
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.id
     *
     * @return the value of National_Data.id
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.id
     *
     * @param id the value for National_Data.id
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.confirmed_Count
     *
     * @return the value of National_Data.confirmed_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getConfirmedCount() {
        return confirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.confirmed_Count
     *
     * @param confirmedCount the value for National_Data.confirmed_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setConfirmedCount(String confirmedCount) {
        this.confirmedCount = confirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.confirmed_Count_Incr
     *
     * @return the value of National_Data.confirmed_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getConfirmedCountIncr() {
        return confirmedCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.confirmed_Count_Incr
     *
     * @param confirmedCountIncr the value for National_Data.confirmed_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setConfirmedCountIncr(String confirmedCountIncr) {
        this.confirmedCountIncr = confirmedCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.suspected_Count
     *
     * @return the value of National_Data.suspected_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getSuspectedCount() {
        return suspectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.suspected_Count
     *
     * @param suspectedCount the value for National_Data.suspected_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setSuspectedCount(String suspectedCount) {
        this.suspectedCount = suspectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.suspected_Count_Incr
     *
     * @return the value of National_Data.suspected_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getSuspectedCountIncr() {
        return suspectedCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.suspected_Count_Incr
     *
     * @param suspectedCountIncr the value for National_Data.suspected_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setSuspectedCountIncr(String suspectedCountIncr) {
        this.suspectedCountIncr = suspectedCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.cured_Count
     *
     * @return the value of National_Data.cured_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getCuredCount() {
        return curedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.cured_Count
     *
     * @param curedCount the value for National_Data.cured_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setCuredCount(String curedCount) {
        this.curedCount = curedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.cured_Count_Incr
     *
     * @return the value of National_Data.cured_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getCuredCountIncr() {
        return curedCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.cured_Count_Incr
     *
     * @param curedCountIncr the value for National_Data.cured_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setCuredCountIncr(String curedCountIncr) {
        this.curedCountIncr = curedCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.dead_Count
     *
     * @return the value of National_Data.dead_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getDeadCount() {
        return deadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.dead_Count
     *
     * @param deadCount the value for National_Data.dead_Count
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setDeadCount(String deadCount) {
        this.deadCount = deadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.dead_Count_Incr
     *
     * @return the value of National_Data.dead_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public String getDeadCountIncr() {
        return deadCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.dead_Count_Incr
     *
     * @param deadCountIncr the value for National_Data.dead_Count_Incr
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setDeadCountIncr(String deadCountIncr) {
        this.deadCountIncr = deadCountIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column National_Data.create_Time
     *
     * @return the value of National_Data.create_Time
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column National_Data.create_Time
     *
     * @param createTime the value for National_Data.create_Time
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
