package com.wentao.ncov.entity.mysql;

import java.util.Date;

public class ProvinceData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.id
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.country_Type
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private String countryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.continents
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private String continents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.province_Name
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.province_Short_Name
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private String provinceShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.comment
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.location_Id
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.crawl_Time
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private Date crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.country
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.create_Time
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Province_data.modify_Time
     *
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.id
     *
     * @return the value of Province_data.id
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.id
     *
     * @param id the value for Province_data.id
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.country_Type
     *
     * @return the value of Province_data.country_Type
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public String getCountryType() {
        return countryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.country_Type
     *
     * @param countryType the value for Province_data.country_Type
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setCountryType(String countryType) {
        this.countryType = countryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.continents
     *
     * @return the value of Province_data.continents
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public String getContinents() {
        return continents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.continents
     *
     * @param continents the value for Province_data.continents
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setContinents(String continents) {
        this.continents = continents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.province_Name
     *
     * @return the value of Province_data.province_Name
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.province_Name
     *
     * @param provinceName the value for Province_data.province_Name
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.province_Short_Name
     *
     * @return the value of Province_data.province_Short_Name
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public String getProvinceShortName() {
        return provinceShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.province_Short_Name
     *
     * @param provinceShortName the value for Province_data.province_Short_Name
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setProvinceShortName(String provinceShortName) {
        this.provinceShortName = provinceShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.comment
     *
     * @return the value of Province_data.comment
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.comment
     *
     * @param comment the value for Province_data.comment
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.location_Id
     *
     * @return the value of Province_data.location_Id
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.location_Id
     *
     * @param locationId the value for Province_data.location_Id
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.crawl_Time
     *
     * @return the value of Province_data.crawl_Time
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.crawl_Time
     *
     * @param crawlTime the value for Province_data.crawl_Time
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.country
     *
     * @return the value of Province_data.country
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.country
     *
     * @param country the value for Province_data.country
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.create_Time
     *
     * @return the value of Province_data.create_Time
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.create_Time
     *
     * @param createTime the value for Province_data.create_Time
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Province_data.modify_Time
     *
     * @return the value of Province_data.modify_Time
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Province_data.modify_Time
     *
     * @param modifyTime the value for Province_data.modify_Time
     * @mbggenerated Tue Feb 11 17:37:58 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}
