package com.wentao.ncov.mappers;

import com.wentao.ncov.entity.mysql.AreaData;
import com.wentao.ncov.entity.mysql.ProvinceData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface AreaDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbggenerated Mon Feb 10 17:44:31 CST 2020
     */
    int insert(AreaData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbggenerated Mon Feb 10 17:44:31 CST 2020
     */
    List<AreaData> selectAll();

    /**
     * 批量插入数据
     *
     * @param areaDataList
     * @return
     * @throws
     * @author wentao
     * @time 2020年02月10日
     * Gods bless me,code never with bug.
     */
    Integer insertAll(@Param("list") List<AreaData> areaDataList);

    /**
     * 根据时间获取数据
     *
     * @param provinceDataListForCheckDouble
     * @param time
     * @return
     * @throws
     * @author wentao
     * @time 2020年02月13日
     * Gods bless me,code never with bug.
     */
    List<AreaData> selectDataByUpdate(@Param("list") List<ProvinceData> provinceDataListForCheckDouble, @Param("date") Date time);
}
