package com.wentao.ncov.mappers;

import com.wentao.ncov.entity.mysql.AreaData;
import com.wentao.ncov.entity.mysql.ProvinceData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AreaDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    int insert(AreaData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_data
     *
     * @mbggenerated Tue Mar 03 14:56:37 CST 2020
     */
    List<AreaData> selectAll();

    /**
     * 批量插入数据
     *
     * @param areaDataList
     * @return
     * @throws
     * @author wentao
     * @time 2020年02月10日
     * Gods bless me,code never with bug.
     */
    Integer insertAll(@Param("list") List<com.wentao.ncov.entity.mysql.AreaData> areaDataList);

    /**
     * 根据时间获取数据
     *
     * @param provinceDataListForCheckDouble
     * @param time
     * @return
     * @throws
     * @author wentao
     * @time 2020年02月13日
     * Gods bless me,code never with bug.
     */
    List<com.wentao.ncov.entity.mysql.AreaData> selectDataByUpdate(@Param("list") List<ProvinceData> provinceDataListForCheckDouble, @Param("date") String time);

    /**
     * 根据省份获取更新时间为最近的数据
     *
     * @param provinceForNull
     * @return
     * @throws
     * @author wentao
     * @time 2020年02月14日
     * Gods bless me,code never with bug.
     */
    List<com.wentao.ncov.entity.mysql.AreaData> selectDataByProvince(@Param("list") List<ProvinceData> provinceForNull);

    List<com.wentao.ncov.entity.mysql.AreaData> selectByUpdateTime(@Param("date") String startDate, @Param("country") String co);
}
