package com.wentao.ncov.mappers;

import com.wentao.ncov.entity.mysql.AreaData;
import com.wentao.ncov.entity.mysql.CityData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface CityDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    int insert(CityData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    CityData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    List<CityData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    int updateByPrimaryKey(CityData record);

    Integer insertAll(@Param("list") List<CityData> cityDataList);

    /**
     * 根据父locationID和日期查询
     *
     * @param areaDataListForYesterday
     * @param time
     * @return
     * @throws
     * @author wentao
     * @time 2020年02月13日
     * Gods bless me,code never with bug.
     */
    List<CityData> selectDataByLocationIdAndcreateTime(@Param("list") List<AreaData> areaDataListForYesterday, @Param("date") Date time);
}
