package com.wentao.ncov.mappers;


import com.wentao.ncov.entity.mysql.NationalData;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface NationalDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table National_Data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table National_Data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    int insert(NationalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table National_Data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    NationalData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table National_Data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    List<NationalData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table National_Data
     *
     * @mbggenerated Tue Mar 03 14:56:38 CST 2020
     */
    int updateByPrimaryKey(NationalData record);
}
